version: '3'

services:
  app:
    build: .
    restart: on-failure
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      DATABASE_URL: postgres://pos:0000@postgres:5432/pos
      SESSION_SECRET: secret
      SESSION_EXPIRY: 28800000
    command: npm start
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pos
      POSTGRES_PASSWORD: '0000'
      POSTGRES_DB: pos
